services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Astana2026!Bigdata
      - POSTGRES_DB=flood
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ".env.prod"
    depends_on:
      - db

  gateway:
    image: nginx:alpine
    container_name: gateway
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - data-service
      - tiles-service

  auth-service:
    container_name: auth-service
    build:
      context: ./services/auth
      dockerfile: Dockerfile
      target: runner
    restart: always
    expose:
      - "3000"
    env_file:
      - ".env.prod"
    depends_on:
      - db

  data-service:
    container_name: data-service
    build:
      context: ./services/data
      dockerfile: Dockerfile
      target: runner
    restart: always
    expose:
      - "3000"
    volumes:
      - ./libs:/app/libs
    env_file:
      - ".env.prod"
    depends_on:
      - db

  tiles-service:
    container_name: tiles-service
    build:
      context: ./services/tiles
      dockerfile: Dockerfile
      target: runner
    restart: always
    expose:
      - "3000"
      - "5000"
    volumes:
      - ./uploads:/app/uploads
      - ./libs:/app/libs
    env_file:
      - ".env.prod"
    environment:
      - UPLOADS_PATH=/app/uploads
      - TILESERVER_CONFIG_PATH=/app/uploads/tileserver-config
      - GRPC_URL=0.0.0.0:5000
    depends_on:
      - db

volumes:
  db_data:
  tiles_uploads:
